AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Aplicação Ingresso Legais Spring Boot com AWS SAM

Resources:
  IngressoLegaisFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: construcao_software.ingresso_back.infrastructure.config.LambdaHandler
      Runtime: java17  # Certifique-se de que esta é a versão correta
      CodeUri: ../ingressoLegais/
      MemorySize: 1024
      Timeout: 30
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
