name: CI - Build, Test, and Dockerize Spring Boot API

on:
  push:
    branches:
      - pipeline/docker
  pull_request:
    branches:
      - pipeline/docker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test Spring Boot application
        run: ./mvnw clean verify

      - name: Build Docker image
        run: docker build -t your_dockerhub_username/spring-boot-api:${{ github.sha }} .

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # - name: Push Docker image
      #   run: docker push your_dockerhub_username/spring-boot-api:${{ github.sha }}
