name: CI/CD Pipeline - Build, Test, Dockerize, and Deploy Spring Boot API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Setup Infrastructure with Terraform
    runs-on: ubuntu-latest


    outputs:
      lambda_bucket_name: ${{ steps.capture_outputs.outputs.lambda_bucket_name }}
      api_id: ${{ steps.capture_outputs.outputs.api_id }}
      proxy_resource_id: ${{ steps.capture_outputs.outputs.proxy_resource_id }}
      account_id: ${{ steps.capture_outputs.outputs.account_id }}
      db_address: ${{ steps.capture_outputs.outputs.db_address }}
      db_name: ${{ steps.capture_outputs.outputs.db_name }}
      db_username: ${{ steps.capture_outputs.outputs.db_username }}
      db_password: ${{ steps.capture_outputs.outputs.db_password }}
      lambda_role_arn: ${{ steps.capture_outputs.outputs.lambda_role_arn }}

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1


      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: ./.infra 
        run: terraform init

      - name: Terraform Plan
        working-directory: ./.infra
        env:
          DB_PASSWORD_SECRET_ARN: ${{ secrets.DB_PASSWORD_SECRET_ARN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: us-east-1
        run: terraform plan -var="db_password_secret_arn=$DB_PASSWORD_SECRET_ARN" -out=tfplan

      - name: Terraform Apply
        working-directory: ./.infra
        env:
          DB_PASSWORD_SECRET_ARN: ${{ secrets.DB_PASSWORD_SECRET_ARN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        run: terraform apply -auto-approve tfplan

      - name: Capture Terraform Outputs
        id: capture_outputs
        working-directory: ./.infra
        run: |
          terraform_output=$(terraform output -json)
          echo "lambda_bucket_name=$(echo $terraform_output | jq -r '.lambda_bucket_name.value')" >> $GITHUB_OUTPUT
          echo "api_id=$(echo $terraform_output | jq -r '.api_id.value')" >> $GITHUB_OUTPUT
          echo "proxy_resource_id=$(echo $terraform_output | jq -r '.proxy_resource_id.value')" >> $GITHUB_OUTPUT
          echo "account_id=$(echo $terraform_output | jq -r '.account_id.value')" >> $GITHUB_OUTPUT
          echo "db_address=$(echo $terraform_output | jq -r '.my_db_address.value')" >> $GITHUB_OUTPUT
          echo "db_name=$(echo $terraform_output | jq -r '.my_db_name.value')" >> $GITHUB_OUTPUT
          echo "db_username=$(echo $terraform_output | jq -r '.my_db_username.value')" >> $GITHUB_OUTPUT
          echo "db_password=$(echo $terraform_output | jq -r '.my_db_password.value')" >> $GITHUB_OUTPUT
          echo "lambda_role_arn=$(echo $terraform_output | jq -r '.lambda_role_arn.value')" >> $GITHUB_OUTPUT

  build:
    name: Build and Test Spring Boot Application
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: ingresso_legais
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root --password=root_password"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Cache Maven Packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to start..."
          for i in {1..20}; do
            if mysqladmin ping -h 127.0.0.1 -u root --password=root_password; then
              echo "MySQL is up and running"
              break
            fi
            echo "MySQL is unavailable - sleeping"
            sleep 10
          done

      - name: Build and Test Application
        working-directory: ./ingressoLegais
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/ingresso_legais?createDatabaseIfNotExist=true
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root_password
        run: ./mvnw clean verify -X

      - name: Upload JAR as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ingress-back-jar
          path: ./ingressoLegais/target/ingresso_back-1.0.0.jar

  deploy:
    name: Deploy to AWS Lambda and API Gateway
    runs-on: ubuntu-latest
    needs: [terraform, build] # Depende dos jobs de Terraform e Build

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Download JAR Artifact
        uses: actions/download-artifact@v3
        with:
          name: ingress-back-jar
          path: ./ingressoLegais/target/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Altere para sua região

      - name: Upload JAR to S3
        run: |
          aws s3 cp ingressoLegais/target/ingresso_back-1.0.0.jar s3://${{ needs.terraform.outputs.lambda_bucket_name }}/ingresso_back-1.0.0.jar

      - name: Create or Update Lambda Function
        run: |
          FUNCTION_NAME="tickets-legais-lambda"
          S3_BUCKET=${{ needs.terraform.outputs.lambda_bucket_name }}
          S3_KEY="ingresso_back-1.0.0.jar"
          ROLE_ARN=${{ needs.terraform.outputs.lambda_role_arn }}
          HANDLER="construcao_software.ingresso_back.adapter.handler.LambdaHandler"
          RUNTIME="java11"
          MEMORY_SIZE=1024
          TIMEOUT=30
          ENV_VARS="{\"SPRING_DATASOURCE_URL\":\"jdbc:mysql://${{ needs.terraform.outputs.db_address }}:3306/${{ needs.terraform.outputs.db_name }}\",\"SPRING_DATASOURCE_USERNAME\":\"${{ needs.terraform.outputs.db_username }}\",\"SPRING_DATASOURCE_PASSWORD\":\"${{ needs.terraform.outputs.db_password }}\"}"

          if aws lambda get-function --function-name $FUNCTION_NAME > /dev/null 2>&1; then
            echo "Updating existing Lambda function..."
            aws lambda update-function-code \
              --function-name $FUNCTION_NAME \
              --s3-bucket $S3_BUCKET \
              --s3-key $S3_KEY
          else
            echo "Creating new Lambda function..."
            aws lambda create-function \
              --function-name $FUNCTION_NAME \
              --runtime $RUNTIME \
              --role $ROLE_ARN \
              --handler $HANDLER \
              --code S3Bucket=$S3_BUCKET,S3Key=$S3_KEY \
              --memory-size $MEMORY_SIZE \
              --timeout $TIMEOUT \
              --environment Variables=$ENV_VARS
          fi

      - name: Grant API Gateway Permission to Invoke Lambda
        run: |
          FUNCTION_NAME="tickets-legais-lambda"
          SOURCE_ARN="arn:aws:apigateway:us-east-1::/restapis/${{ needs.terraform.outputs.api_id }}/stages/prod/*/*"

          aws lambda add-permission \
            --function-name $FUNCTION_NAME \
            --statement-id AllowAPIGatewayInvoke \
            --action lambda:InvokeFunction \
            --principal apigateway.amazonaws.com \
            --source-arn $SOURCE_ARN || echo "Permission already exists"

      - name: Update API Gateway Integration
        run: |
          FUNCTION_NAME="tickets-legais-lambda"
          URI="arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:${{ needs.terraform.outputs.account_id }}:function:$FUNCTION_NAME/invocations"

          aws api gateway put-integration \
            --rest-api-id ${{ needs.terraform.outputs.api_id }} \
            --resource-id ${{ needs.terraform.outputs.proxy_resource_id }} \
            --http-method ANY \
            --type AWS_PROXY \
            --integration-http-method POST \
            --uri "$URI"

      - name: Deploy API Gateway
        run: |
          aws api gateway create-deployment \
            --rest-api-id ${{ needs.terraform.outputs.api_id }} \
            --stage-name prod

      - name: Notify Deployment Success (Optional)
        if: success()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "Deploy da Lambda concluído com sucesso! Endpoint: https://${{ needs.terraform.outputs.api_id }}.execute-api.us-east-1.amazonaws.com/prod"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
