name: CI - Build, Test, and Dockerize Spring Boot API

on:
  push:
    branches:
      - pipeline/docker
  pull_request:
    branches:
      - pipeline/docker

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: ingresso_legais
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root --password=root_password || exit 1"
          --health-interval=15s
          --health-timeout=10s
          --health-retries=20

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to start..."
          for i in {1..20}; do
            if mysqladmin ping -h 127.0.0.1 -u root --password=root_password; then
              echo "MySQL is up and running"
              break
            fi
            echo "MySQL is unavailable - sleeping"
            sleep 10
          done

      - name: Build and test Spring Boot application
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/ingresso_legais?createDatabaseIfNotExist=true
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root_password
        run: ./mvnw clean verify

      - name: Check MySQL logs (for debugging)
        if: failure()
        run: |
          echo "MySQL logs for debugging:"
          docker logs $(docker ps -q -f name=mysql)

      - name: Build Docker image
        run: docker build -t your_dockerhub_username/spring-boot-api:${{ github.sha }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image
        run: docker push your_dockerhub_username/spring-boot-api:${{ github.sha }}
